### ISSUE TITLE
Otomatik deploy alınsın

### ISSUE THREAD

**Issue by log101** [periakteon/marka-sorgula#1]
Projeyi Vercel'e veya başka bir platforma (AWS, Cloudflare, vs.) otomatik deploy edebiliriz böylece inceleme ve geliştirme esnasında paylaşıp fikir alma fırsatımız olur. O işi ben halledebilirim, vercel pro hesabım var onun altına alabiliriz dilersen.

**Comment by periakteon** [comment]
Merhaba @log101,

Versiyonlama ve background fetch için bir API servisine ihtiyacımız olacağından "web" klasörünü Vercel'e deploy edeceğim. Bu şekilde, deploy edilen adres üzerinden gerekli verileri API'dan sağlayabiliriz ihtiyacı olana. Belki uzun vadede web uygulamasını da geliştirebilirim ancak önceliğim mobil tarafında. İsteyenler tabii ki web için PR atabilir, inceleyip merge edebilirim main'e. Jest'i kurup deploy edeceğim Vercel'e en kısa zamanda.

**Comment by log101** [comment]
API olarak kullanacaksın, anladım 👍 Mobil konusunda çok tecrübem yok ama ufak tefek işleri alabilirim belki işlerini kolaylaştırmak adına, kolaylıklar 🙌

**Comment by periakteon** [comment]
Evet, öyle yapmayı planlıyorum; v2 gibi bir update geçtiğimde yeni client ve eski client'ları da stabil olarak devam ettirebilmek için :)

Çok teşekkür ederim. Şu anlık en acil olanı markalarla ilgili bilgilerin ve neden boykot edilmesi gerektiğine dair ispatların yer aldığı bir JSON dosyası. Bunun için yardıma ihtiyacım var. Bununla ilgili bir issue template'i oluşturacağım bu akşam inşallah.
